image: docker:latest

stages:
  - build

before_script:
  - docker -v

build:
  stage: build
  only:
    - tags
  script:
    - docker build -t epb/mpay:t-$CI_BUILD_ID .
    - docker tag epb/mpay:t-$CI_BUILD_ID $CI_REGISTRY/epb360/mpay:$CI_BUILD_TAG
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWD $CI_REGISTRY
    - docker push $CI_REGISTRY/epb360/mpay:$CI_BUILD_TAG